// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/assistant/embedded/v1alpha2/embedded_assistant.proto

package googleAssistant.common;

public interface AssistConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.assistant.embedded.v1alpha2.AssistConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Specifies how to process the subsequent incoming audio. Required if
   * [AssistRequest.audio_in][google.assistant.embedded.v1alpha2.AssistRequest.audio_in] bytes will be provided in subsequent requests.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.AudioInConfig audio_in_config = 1;</code>
   */
  boolean hasAudioInConfig();
  /**
   * <pre>
   * Specifies how to process the subsequent incoming audio. Required if
   * [AssistRequest.audio_in][google.assistant.embedded.v1alpha2.AssistRequest.audio_in] bytes will be provided in subsequent requests.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.AudioInConfig audio_in_config = 1;</code>
   */
  googleAssistant.common.AudioInConfig getAudioInConfig();
  /**
   * <pre>
   * Specifies how to process the subsequent incoming audio. Required if
   * [AssistRequest.audio_in][google.assistant.embedded.v1alpha2.AssistRequest.audio_in] bytes will be provided in subsequent requests.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.AudioInConfig audio_in_config = 1;</code>
   */
  googleAssistant.common.AudioInConfigOrBuilder getAudioInConfigOrBuilder();

  /**
   * <pre>
   * The text input to be sent to the Assistant. This can be populated from a
   * text interface if audio input is not available.
   * </pre>
   *
   * <code>string text_query = 6;</code>
   */
  java.lang.String getTextQuery();
  /**
   * <pre>
   * The text input to be sent to the Assistant. This can be populated from a
   * text interface if audio input is not available.
   * </pre>
   *
   * <code>string text_query = 6;</code>
   */
  com.google.protobuf.ByteString
      getTextQueryBytes();

  /**
   * <pre>
   * *Required* Specifies how to format the audio that will be returned.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.AudioOutConfig audio_out_config = 2;</code>
   */
  boolean hasAudioOutConfig();
  /**
   * <pre>
   * *Required* Specifies how to format the audio that will be returned.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.AudioOutConfig audio_out_config = 2;</code>
   */
  googleAssistant.common.AudioOutConfig getAudioOutConfig();
  /**
   * <pre>
   * *Required* Specifies how to format the audio that will be returned.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.AudioOutConfig audio_out_config = 2;</code>
   */
  googleAssistant.common.AudioOutConfigOrBuilder getAudioOutConfigOrBuilder();

  /**
   * <pre>
   * *Required* Represents the current dialog state.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.DialogStateIn dialog_state_in = 3;</code>
   */
  boolean hasDialogStateIn();
  /**
   * <pre>
   * *Required* Represents the current dialog state.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.DialogStateIn dialog_state_in = 3;</code>
   */
  googleAssistant.common.DialogStateIn getDialogStateIn();
  /**
   * <pre>
   * *Required* Represents the current dialog state.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.DialogStateIn dialog_state_in = 3;</code>
   */
  googleAssistant.common.DialogStateInOrBuilder getDialogStateInOrBuilder();

  /**
   * <pre>
   * Device configuration that uniquely identifies a specific device.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.DeviceConfig device_config = 4;</code>
   */
  boolean hasDeviceConfig();
  /**
   * <pre>
   * Device configuration that uniquely identifies a specific device.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.DeviceConfig device_config = 4;</code>
   */
  googleAssistant.common.DeviceConfig getDeviceConfig();
  /**
   * <pre>
   * Device configuration that uniquely identifies a specific device.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.DeviceConfig device_config = 4;</code>
   */
  googleAssistant.common.DeviceConfigOrBuilder getDeviceConfigOrBuilder();

  public googleAssistant.common.AssistConfig.TypeCase getTypeCase();
}
